export const GET_AUTOCOMPLETE_RESULTS = 'GET_AUTOCOMPLETE_RESULTS'
export const GET_AUTOCOMPLETE_RESULTS_SUCCESS = 'GET_AUTOCOMPLETE_RESULTS_SUCCESS'
export const GET_AUTOCOMPLETE_RESULTS_FAILED = 'GET_AUTOCOMPLETE_RESULTS_FAILED'
