export const GET_PRODUCTS_RESULTS = 'GET_PRODUCTS_RESULTS';
export const GET_PRODUCTS_RESULTS_SUCCESS = 'GET_PRODUCTS_RESULTS_SUCCESS';
export const GET_PRODUCTS_RESULTS_FAILED = 'GET_PRODUCTS_RESULTS_FAILED';